server:
  port: 11000

eureka:
  instance:
    hostname: 192.168.10.191
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.10.168:11020/eureka/
      defaultZone: http://192.168.10.191:11020/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


zuul:
  routes:
    job-rest-service:
      path: /job-rest-service/**
#      service-id: job-rest-service
    customer-rest-service:
      path: /customer-rest-service/**
#      service-id: customer-rest-service
    upload-rest-service:
      path: /upload-rest-service/**
#      service-id: upload-rest-service
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 100000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 100000

ribbon:
  ReadTimeout: 60000

config:
    default-version: v0.1.1
